### ISSUE TITLE
Firefox throws "SyntaxError: invalid regexp group"

### ISSUE THREAD

**Issue by mr-perseus** [thenativeweb/boolean#27] opened 2019-10-31 19:46 UTC
The following regex causes Firefox to throw "SyntaxError: invalid regexp group":
https://github.com/thenativeweb/boolean/blob/bbad0b1bf08a0aa348d6ddc1a9ff7d31d922014f/lib/boolean.ts#L3

Firefox:
<img width="406" alt="Screenshot 2019-10-31 at 20 43 33" src="https://user-images.githubusercontent.com/38375248/67980645-2ff0b280-fc1f-11e9-8f17-bca0b2ddc528.png">

It works fine on Chrome(ium):
<img width="421" alt="Screenshot 2019-10-31 at 20 43 55" src="https://user-images.githubusercontent.com/38375248/67980695-439c1900-fc1f-11e9-9368-bfa3a5cfdba4.png">

**Comment by goloroden** [comment] 2019-10-31 20:11
Hi @mr-perseus 😊 

Thanks for bringing this up!

The problem here is that Firefox doesn't support named capture groups, which is an official feature since EcmaScript 2018 (see https://github.com/tc39/proposal-regexp-named-groups). There is an [open issue to support this in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1362154), and it has been there for *3 years*.

So, first of all, this is a problem caused by Firefox, not being compatible to all ES2018 features…

However, of course, at first sight it would be easy to fix: Simply remove the named capture group, given that we do not even use it. However, it's not that simple, unfortunately :-(

We are developing lots of code for Node.js, and we open-source all the things that are not related to or restricted by IP. Now, we don't want to have different linting rules in ~ 300 repositories, partially public, partially private. Instead we rely on [a single set of linting rules](https://www.npmjs.com/package/eslint-config-es) for all of our modules.

Generally speaking, named capture groups make lots of sense for us, since it helps to make regexs more readable, which is why we enforce this. This is a good thing for 99.9% of our code. Unfortunately, since this is part of the general ESLint rules, this rule is applied to the `boolean` module as well.

Of course we could turn off this specific rule here, but then you need to document why this was done, and you need to keep track of it, so that you can remove it again once it's not needed any more. And worse: This would be a precedent case, because if it's okay to change ESLint rules in *one* module, why not do it in a second, third, fourth, … and so on?

In the end this leads to uncontrolled changes in linting rules, for code that works as-is for *us*.

So, to cut a long story short: This is why it is like it is, and this is why it's unlikely that we are going to change this – especially given that the cause of the error is Firefox's incomplete support for ES2018, not our code.

However, the same question was asked by @sulabhjain in #17, so there seems to be some demand – and given how widely used this module is (more than 130k downloads per week on npm) – we maybe should give this a second thought.

One option would be to comment the questionable line, add a Firefox-compatible implementation after the commented line, and add a big comment on why this was done, with a link to the aforementioned issue and maybe a link to the awesome kangax table (see https://kangax.github.io/compat-table/es2016plus/#test-RegExp_named_capture_groups), so that this can be checked from time to time, whether this is actually still needed.

Could you imagine coming up with a PR for this, that works in the aforementioned way?

**Comment by mr-perseus** [comment] 2019-10-31 21:54
Hi @goloroden 

Thank you very much for this detailed explanation. I agree with your opinion that this should be fixed in Firefox and that it's bad to disable lint rules like this. I opened PR #28 for this.

**Comment by goloroden** [comment] 2019-11-01 09:36
@mr-perseus Thanks a lot for the PR, and also for your understanding 😊

I have just merged the PR, and will release a new version to npm in a few minutes.

**Closed by goloroden** 2019-11-01 09:36 UTC

**Comment by goloroden** [comment] 2019-11-01 09:43
PS: `boolean@2.0.3` is available on npm, which includes the fix 😊

**Comment by mr-perseus** [comment] 2019-11-01 12:17
@goloroden Thanks for merging and releasing 2.0.3. :)

**Comment by goloroden** [comment] 2019-11-01 13:30
You’re welcome 😊
